Start kube-controller-manager with --cluster-cidr and --allocate-node-cidrs options to support CNI Plugins (e.g. Antrea)
vmware/ansible-coreos-kubernetes-master pull request #42
Opened 2020-02-28 00:13 UTC by alex-vmw

Start kube-controller-manager with --cluster-cidr and --allocate-node-cidrs options to support CNI Plugins (e.g. Antrea)

2020-02-28 00:24 UTC, puneetkatyal requested changes

2020-02-28 00:24 UTC, puneetkatyal commented on templates/kube-controller-manager.yaml
> +    - --cluster-cidr={{kubernetes_cluster_cidr}}
Can we have a boolean variable `kubernetes_enable_cni` so these options are added only when it is set to `true`?

2020-02-28 03:29 UTC, naveens approved these changes
LGTM

2020-03-02 20:13 UTC, puneetkatyal approved these changes

2020-03-02 20:27 UTC, merged