Ensure kube scheduler policy config dir exists
vmware/ansible-coreos-kubernetes-master pull request #8
Opened 2017-07-06 13:03 UTC by raja-gola

2017-07-06 15:25 UTC, imkin commented
Please add description and information on what this change is trying to accomplish.

2017-07-07 06:45 UTC, raja-gola commented
description added

2017-07-10 18:52 UTC, imkin commented on tasks/main.yml
> +- name: ensures kube scheduler policy config dir exists
should we also set the mode of the directory?

2017-07-11 04:50 UTC, puneetkatyal commented on tasks/main.yml
> +- name: ensures kube scheduler policy config dir exists
we should.

2017-07-11 18:16 UTC, imkin requested changes
Providing the same comment to "Request Changes"

Add "mode" to the creation of the directory.

2017-07-12 05:23 UTC, raja-gola reviewed
added mode=0755 for dir

2017-07-12 05:23 UTC, raja-gola commented on tasks/main.yml
> +- name: ensures kube scheduler policy config dir exists
added mode=0755 for dir

2017-07-14 15:55 UTC, imkin commented on tasks/main.yml
> +- name: ensures kube scheduler policy config dir exists
Is the mode that it gets copied by default?

2017-07-14 19:35 UTC, imkin approved these changes

2017-07-14 19:35 UTC, imkin commented on tasks/main.yml
> +- name: ensures kube scheduler policy config dir exists
755 should be fine. As the "core" user might want to read. Maybe 750 is fine too. Approving.

2017-07-14 19:36 UTC, imkin commented
Do not see any comments or issues by anyone else. Hence merging.

2017-07-14 19:36 UTC, merged